---
- name: Install dependencies
  become: true
  become_method: sudo
  yum:
    enablerepo: base-debuginfo
    name: "{{ item }}"
    state: present
  with_items:
    - systemtap
    - "kernel-debuginfo-{{ ansible_kernel }}"
    - "kernel-devel-{{ ansible_kernel }}"

- name: Generate the stap module
  become: true
  become_method: sudo
  shell: "staprun -L $(stap -p4 -g /root/CVE-2016-5195.stap)"
  register: stap_mod_install

- debug:
    var: stap_mod_install
