---
- name: Install dependencies
  become: true
  become_method: sudo
  yum:
    enablerepo: base-debuginfo
    name: "{{ item }}"
    state: latest
  with_items:
    - systemtap
    - "kernel-debuginfo-{{ ansible_kernel }}"
    - "kernel-devel-{{ ansible_kernel }}"

- name: Generate the stap module
  become: true
  become_method: sudo
  shell: "stap -p4 -g /root/cve-2016-5195.stap"
  register: stap_mod_gen

- name: Install the module
  become: true
  become_method: sudo
  shell: "staprun -L /root/.systemtap/cache/bb/stap_bbdee39c313c02b1757818d71b4e5c1a_65687.ko"
  register: stap_mod_install

- debug:
    var: stap_mod_install
