---
- name:
  become: true
  become_method: sudo
  copy:
    src: cve-2016-5195/cve-2016-5195.stap
    dest: /root/cve-2016-5195.stap
    owner: root
    group: root
    mode: 0600

- block:
  - name: Install dependencies
    become: true
    become_method: sudo
    yum:
      enablerepo: base-debuginfo
      name: "{{ item }}"
      state: present
    with_items:
      - systemtap
      - "kernel-debuginfo-{{ ansible_kernel }}"
      - "kernel-devel-{{ ansible_kernel }}"

  - name: Generate and load the stap module
    become: true
    become_method: sudo
    shell: "staprun -L $(stap -p4 -g /root/cve-2016-5195.stap)"
    register: stap_mod_install
    failed_when: "'File exists' not in stap_mod_install.stderr"

  rescue:
  - debug:
      msg: "Something is fucked"

  always:
  - name: Remove the stap file
    become: true
    become_method: sudo
    file:
      path: /root/cve-2016-5195.stap
      state: absent
