---
- block:
  become: true
  become_method: sudo
  - name: Install dependencies
    yum:
      enablerepo: base-debuginfo
      name: "{{ item }}"
      state: present
    with_items:
      - systemtap
      - "kernel-debuginfo-{{ ansible_kernel }}"
      - "kernel-devel-{{ ansible_kernel }}"

  - name: Generate and load the stap module
    shell: "staprun -L $(stap -p4 -g /root/CVE-2016-5195.stap)"
    register: stap_mod_install
    failed_when: "'File exists' not in stap_mod_install.stderr"
    changed_when: False

  rescue:
  - debug:
      msg: "Something is fucked"
